version: "3.5"

services:
  backend:
    restart: unless-stopped
    container_name: backend
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    command: npm run start
    ports:
      - "3000:3000"
    networks:
      - painel
    depends_on:
      - postgres
    environment:
      - PORT=3000

  frontend:
    restart: unless-stopped
    container_name: frontend
    # volumes:
    #   - ./nginx/conf/:/etc/nginx/conf.d/:ro
    #   - ./certbot/www:/var/www/certbot/:ro
    #   - ./certbot/conf/:/etc/nginx/ssl/:ro
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
      - "443:443"

  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot/:rw
  #     - ./certbot/conf/:/etc/letsencrypt/:rw

  postgres:
    container_name: postgresdb
    image: postgres:14.1-alpine
    restart: always
    networks:
      - painel
    environment:
      - POSTGRES_USER=eleva
      - POSTGRES_PASSWORD=midiaindooreleva84
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    networks:
      - painel
    environment:
      PGADMIN_DEFAULT_EMAIL: stanlley41@gmail.com
      PGADMIN_DEFAULT_PASSWORD: midiadigitaleleva84
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin-data:/var/lib/pgadminql/data

    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  db:
    driver: local

networks:
  painel:
    external: true
